Android allHDRoots
uport-project/react-native-uport-signer pull request #8
Opened 2019-03-19 09:44 UTC by simonas-notcat

This PR adds allHDRoots method

2019-03-27 15:43 UTC, simonas-notcat commented
Also we need to make sure, that the same functionality is available on iOS. cc @aldigjo

2019-04-03 13:41 UTC, mirceanis requested changes
Thanks for the addition.
There is an equivalent method on iOS that is already exposed as a react method.
For parity and continuity, I requested a rename.

2019-04-03 13:41 UTC, mirceanis commented on android/src/main/java/com/reactlibrary/RNUportHDSignerModule.kt
> +    fun allHDRoots(promise: Promise?) {
The equivalent method on iOS is named `listSeedAddresses`
I suggest using the same name here:

```suggestion
    fun listSeedAddresses(promise: Promise?) {
```

2019-04-04 11:36 UTC, mirceanis approved these changes

2019-04-04 11:36 UTC, merged